// Re-fetches cover art -- from iTunes' public Search API first, falling back
// to MusicBrainz + Cover Art Archive when iTunes has nothing (better
// metadata coverage for HK/TW Cantopop and other regional releases, though
// sparser actual image coverage) -- and replaces whatever's currently in D1
// (missing, or a bad/placeholder image some ripper embedded in the source
// files). Uploads the new artwork to the Telegram channel exactly like
// scripts/import.ts does for embedded covers — the audio tracks themselves
// are never touched.
//
// Usage:
//   npm run fix-covers -- [--limit=N] [--force] [--dry-run] [--retry-failed] [--loose-fallback] [--fallback-cover]
//
// Tries an album-level match first (artist + album name). A lot of this
// library's "albums" are actually a single artist's unrelated singles
// lumped together under one folder-derived name (e.g. "12古风歌曲") because
// scripts/import.ts groups tracks by (artist, album name) — iTunes obviously
// has no such "album", and even if it did, one cover can't represent songs
// that aren't really from the same release. So when the album-level search
// finds nothing, this falls back to searching per SONG (artist + track
// title) and stores the result on that one track (tracks.cover_ref) instead
// of the album. If even the exact song search misses, and --loose-fallback
// is set, it takes the artist's top iTunes hit as a "related, not exact"
// cover rather than leaving the track with nothing. If that also misses
// and --fallback-cover is set, the track gets docs/music-cover.jpg instead
// (uploaded once, then the same Telegram ref is reused for every track that
// falls this far).
//
// By default only a NULL cover_ref is touched (safe — can't make things
// worse) -- EXCEPT when LOCAL_MUSIC_DIR is set (see .env.example) and the
// track's source file's embedded picture is tagged desc="AutoGenerated"
// (the marker scripts/import.ts also checks, written by local tools like
// fix_mp3_tags.py for their own generated color-block placeholders): those
// are known-bad regardless of what's currently in cover_ref, so they're
// replaced even without --force. Pass --force to replace everything else
// that already has a cover_ref too. Progress is saved to
// .cover-fix-state.json so re-running the same command resumes where it
// left off instead of re-querying iTunes/re-reading local files for entries
// already handled; --retry-failed clears "no-match"/"error" entries so
// they're attempted again.
import "dotenv/config";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseFile } from "music-metadata";
import * as OpenCC from "opencc-js";

const LIMIT = (() => {
  const arg = process.argv.find((a) => a.startsWith("--limit="));
  return arg ? Number(arg.slice("--limit=".length)) : 20;
})();
const FORCE = process.argv.includes("--force");
const DRY_RUN = process.argv.includes("--dry-run");
const RETRY_FAILED = process.argv.includes("--retry-failed");
const LOOSE_FALLBACK = process.argv.includes("--loose-fallback");
const FALLBACK_COVER = process.argv.includes("--fallback-cover");

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing env var ${name} (see .env.example)`);
    process.exit(1);
  }
  return v;
}

const TG_BOT_TOKEN = requireEnv("TG_BOT_TOKEN");
const TG_CHANNEL_ID = requireEnv("TG_CHANNEL_ID");
const CF_ACCOUNT_ID = requireEnv("CF_ACCOUNT_ID");
const CF_API_TOKEN = requireEnv("CF_API_TOKEN");
const D1_DATABASE_ID = requireEnv("D1_DATABASE_ID");

// Optional: without it, the only way to touch an already-covered
// album/track is --force.
const LOCAL_MUSIC_DIR = process.env.LOCAL_MUSIC_DIR;
if (!LOCAL_MUSIC_DIR) {
  console.warn("LOCAL_MUSIC_DIR not set — can't detect AutoGenerated placeholders still sitting in cover_ref; only --force will touch those.\n");
}

const AUTOGENERATED_COVER_DESC = "AutoGenerated";

const STATE_FILE = path.join(process.cwd(), ".cover-fix-state.json");

// Last-resort cover for tracks where nothing (iTunes, MusicBrainz, or the
// loose fallback) turns anything up. A shared generic image is the same
// category of thing as the "AutoGenerated" placeholders this whole script
// exists to clean up -- the difference is this one's a deliberate choice
// with a picture the user actually likes, uploaded once and reused by
// reference, not a script silently stamping color blocks. Opt-in via
// --fallback-cover so a plain run never applies it without being asked.
const FALLBACK_COVER_PATH = path.join(process.cwd(), "docs/music-cover.jpg");
const FALLBACK_COVER_REF_FILE = path.join(process.cwd(), ".cover-fallback-ref.json");

// iTunes has separate storefronts per country and a release only shows up
// in the ones it was distributed to — try a handful likely to cover a
// mixed CN/JP/Western library before giving up.
const STOREFRONTS = ["us", "cn", "tw", "hk", "jp", "gb"];
const ITUNES_DELAY_MS = 3200; // Apple's search endpoint allows ~20 req/min
const ITUNES_RATE_LIMIT_RETRIES = 3;
const ITUNES_RATE_LIMIT_BACKOFF_MS = 8000;

type Album = { id: string; name: string; artist_name: string; cover_ref: string | null; sample_source_path: string | null };
type Track = { id: string; title: string; cover_ref: string | null; source_path: string | null };
// Keys are "album-search:<id>" (cached album-name lookup result),
// "track:<id>" (a track-level fix attempt), or "local-autogen:<id>" (cached
// verdict from checking the local source file's embedded picture).
type EntryStatus = "fixed" | "fixed-loose" | "fixed-fallback" | "no-match" | "error" | "autogen" | "not-autogen";
type State = Record<string, EntryStatus>;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function loadState(): Promise<State> {
  try {
    return JSON.parse(await readFile(STATE_FILE, "utf-8"));
  } catch {
    return {};
  }
}

async function saveState(state: State): Promise<void> {
  await writeFile(STATE_FILE, JSON.stringify(state, null, 2));
}

async function d1<T = any>(sql: string, params: unknown[] = []): Promise<T[]> {
  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/d1/database/${D1_DATABASE_ID}/query`,
    {
      method: "POST",
      headers: { Authorization: `Bearer ${CF_API_TOKEN}`, "Content-Type": "application/json" },
      body: JSON.stringify({ sql, params }),
    },
  );
  const data = (await res.json()) as any;
  if (!data.success) throw new Error(`D1 query failed: ${JSON.stringify(data.errors)}`);
  return data.result[0]?.results ?? [];
}

// Checks the local source file's embedded picture for the same
// desc="AutoGenerated" marker scripts/import.ts skips on new imports (see
// its AUTOGENERATED_COVER_DESC). Used to catch albums/tracks that were
// imported before that check existed, so they don't require --force.
async function isLocallyAutoGenerated(sourcePath: string | null): Promise<boolean> {
  if (!LOCAL_MUSIC_DIR || !sourcePath) return false;
  try {
    const meta = await parseFile(path.join(LOCAL_MUSIC_DIR, sourcePath), { duration: false, skipCovers: false });
    return meta.common.picture?.[0]?.description === AUTOGENERATED_COVER_DESC;
  } catch {
    return false;
  }
}

// Whether an album/track should be considered for fixing at all: no cover
// yet, --force is on, or (cached after the first check) its current cover
// is a locally-confirmed AutoGenerated placeholder.
async function needsFixing(cacheKey: string, coverRef: string | null, sourcePath: string | null, state: State): Promise<boolean> {
  if (!coverRef) return true;
  if (FORCE) return true;
  if (state[cacheKey] === "autogen") return true;
  if (state[cacheKey] === "not-autogen") return false;
  const isAutoGen = await isLocallyAutoGenerated(sourcePath);
  state[cacheKey] = isAutoGen ? "autogen" : "not-autogen";
  return isAutoGen;
}

// iTunes' HK/TW storefronts (where a lot of the Cantopop/older Mandopop in
// this library actually lives) tag titles in Traditional Chinese, while the
// local library is Simplified -- e.g. "海闊天空" vs "海阔天空". Without this,
// those are just different strings and every such match silently fails.
const toSimplified = OpenCC.Converter({ from: "tw", to: "cn" });

// Loose match: convert to Simplified, strip punctuation/case, and require
// one side to contain the other. Good enough to reject "Greatest Hits"
// matching everything while still allowing "深呼吸 (Deluxe Edition)" to
// match "深呼吸".
function normalize(s: string): string {
  return toSimplified(s)
    .toLowerCase()
    .replace(/\(.*?\)|\[.*?\]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "")
    .trim();
}

// Local track titles often carry import-time junk -- a leading track number
// ("06.", "18.") and/or the artist's own name repeated before a " - "
// separator (e.g. "06.刘德华 -  谢谢您的爱"). iTunes' fuzzy search mostly
// shrugs this off, but it's poison for MusicBrainz's Lucene query syntax:
// those extra terms can push the real recording clean out of the top
// results. Used to build the actual search term, not just for comparison.
function cleanTrackTitle(title: string, artist: string): string {
  let t = title.replace(/^\d+[.\s]+/, "");
  const artistPattern = artist.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  t = t.replace(new RegExp(`^${artistPattern}\\s*[-–—]\\s*`, "i"), "");
  t = t.replace(/\s{2,}/g, " ").trim();
  return t || title;
}

function textMatches(want: string, got: string): boolean {
  const w = normalize(want);
  const g = normalize(got);
  return !!w && !!g && (g.includes(w) || w.includes(g));
}

type ItunesAlbum = { artistName: string; collectionName: string; artworkUrl100: string };
type ItunesSong = { artistName: string; trackName: string; artworkUrl100: string };

// Generic iTunes Search API lookup, tried across storefronts until `matches`
// picks a hit. Shared by the album search, the exact song search, and the
// loose artist-only fallback below.
// Apple rate-limits this endpoint (no Retry-After header, and it returns
// either 403 or 429 depending on which edge answers) at a pace well below
// what a naive per-country loop produces. A rate-limited response is NOT
// "no results" -- treating it that way silently turns real matches into
// false "no confident match"es. So on 403/429 we back off and retry the
// SAME country a few times before giving up on it.
async function fetchItunesJson<T>(url: string): Promise<{ results: T[] } | null> {
  for (let attempt = 0; attempt <= ITUNES_RATE_LIMIT_RETRIES; attempt++) {
    const res = await fetch(url);
    if (res.status === 403 || res.status === 429) {
      console.warn(`  iTunes rate-limited, backing off ${ITUNES_RATE_LIMIT_BACKOFF_MS / 1000}s...`);
      await sleep(ITUNES_RATE_LIMIT_BACKOFF_MS * (attempt + 1));
      continue;
    }
    if (!res.ok) return null;
    return (await res.json()) as { results: T[] };
  }
  console.warn("  iTunes still rate-limited after retries, giving up on this storefront");
  return null;
}

async function searchItunes<T extends { artworkUrl100: string }>(
  term: string,
  entity: "album" | "song",
  matches: (r: T) => boolean,
): Promise<T | null> {
  const q = encodeURIComponent(term);
  for (const country of STOREFRONTS) {
    await sleep(ITUNES_DELAY_MS);
    try {
      const data = await fetchItunesJson<T>(
        `https://itunes.apple.com/search?term=${q}&entity=${entity}&limit=5&country=${country}`,
      );
      const hit = data?.results.find(matches);
      if (hit) return hit;
    } catch (err) {
      console.warn(`  iTunes lookup failed (${country}): ${err}`);
    }
  }
  return null;
}

function artworkUrl(hit: { artworkUrl100: string }): string {
  return hit.artworkUrl100.replace(/\d+x\d+bb/, "1200x1200bb");
}

// Secondary source, tried only when iTunes has nothing: MusicBrainz has much
// better metadata coverage for HK/TW Cantopop and other regional releases
// than iTunes' catalog, but Cover Art Archive (the images themselves) is a
// sparser, community-uploaded archive -- most individual releases have no
// image at all, so every release MusicBrainz links to the match gets tried
// before giving up. MusicBrainz strictly enforces ~1 req/sec and asks for
// an identifying User-Agent; Cover Art Archive has no documented limit but
// gets the same courtesy.
const MUSICBRAINZ_USER_AGENT = "subsonic-telegram-cover-fix/1.0 (personal-use script)";
const MUSICBRAINZ_DELAY_MS = 1100;
const COVER_ART_ARCHIVE_DELAY_MS = 300;

function escapeLucene(s: string): string {
  return s.replace(/([+\-&|!(){}[\]^"~*?:\\/])/g, "\\$1");
}

async function musicBrainzFetch(url: string): Promise<any | null> {
  await sleep(MUSICBRAINZ_DELAY_MS);
  try {
    const res = await fetch(url, { headers: { "User-Agent": MUSICBRAINZ_USER_AGENT, Accept: "application/json" } });
    if (!res.ok) return null;
    return await res.json();
  } catch (err) {
    console.warn(`  MusicBrainz lookup failed: ${err}`);
    return null;
  }
}

async function coverArtArchiveFront(releaseMbid: string): Promise<string | null> {
  await sleep(COVER_ART_ARCHIVE_DELAY_MS);
  try {
    const res = await fetch(`https://coverartarchive.org/release/${releaseMbid}`, {
      headers: { Accept: "application/json" },
    });
    if (!res.ok) return null; // 404 is the common case: no art archived for this release
    const data = (await res.json()) as { images?: { front?: boolean; image: string }[] };
    return data.images?.find((i) => i.front)?.image ?? data.images?.[0]?.image ?? null;
  } catch {
    return null;
  }
}

async function searchMusicBrainzAlbumArtwork(artist: string, album: string): Promise<string | null> {
  const q = `artist:${escapeLucene(artist)} AND release:${escapeLucene(album)}`;
  const data = await musicBrainzFetch(`https://musicbrainz.org/ws/2/release?query=${encodeURIComponent(q)}&fmt=json&limit=5`);
  for (const rel of data?.releases ?? []) {
    const artistName = rel["artist-credit"]?.[0]?.name ?? "";
    if (!textMatches(artist, artistName) || !textMatches(album, rel.title ?? "")) continue;
    const art = await coverArtArchiveFront(rel.id);
    if (art) return art;
  }
  return null;
}

async function searchMusicBrainzSongArtwork(artist: string, title: string): Promise<string | null> {
  const q = `artist:${escapeLucene(artist)} AND recording:${escapeLucene(title)}`;
  const data = await musicBrainzFetch(
    `https://musicbrainz.org/ws/2/recording?query=${encodeURIComponent(q)}&fmt=json&limit=5&inc=releases`,
  );
  for (const rec of data?.recordings ?? []) {
    const artistName = rec["artist-credit"]?.[0]?.name ?? "";
    if (!textMatches(artist, artistName) || !textMatches(title, rec.title ?? "")) continue;
    for (const rel of rec.releases ?? []) {
      const art = await coverArtArchiveFront(rel.id);
      if (art) return art;
    }
  }
  return null;
}

async function searchAlbumArtwork(artist: string, album: string): Promise<string | null> {
  const hit = await searchItunes<ItunesAlbum>(
    `${artist} ${album}`,
    "album",
    (r) => textMatches(artist, r.artistName) && textMatches(album, r.collectionName),
  );
  if (hit) return artworkUrl(hit);
  return searchMusicBrainzAlbumArtwork(artist, album);
}

async function searchSongArtwork(artist: string, title: string): Promise<string | null> {
  const hit = await searchItunes<ItunesSong>(
    `${artist} ${title}`,
    "song",
    (r) => textMatches(artist, r.artistName) && textMatches(title, r.trackName),
  );
  if (hit) return artworkUrl(hit);
  return searchMusicBrainzSongArtwork(artist, title);
}

// No exact song match -- grab the artist's top hit as a "related, not
// exact" cover rather than leaving the track with nothing. Only used when
// --loose-fallback is passed, since it can attach the wrong song's art.
async function searchLooseArtwork(artist: string, title: string): Promise<string | null> {
  const hit = await searchItunes<ItunesSong>(artist, "song", (r) => textMatches(artist, r.artistName));
  if (!hit) return null;
  console.log(`  loose match: using artwork from "${hit.trackName}" (exact title "${title}" not found)`);
  return artworkUrl(hit);
}

const UPLOAD_RETRIES = 3;

// Best-effort: requires the bot to hold the channel's "Delete messages"
// admin right, same as TelegramStorage.deleteFile (src/storage/telegram.ts).
// Called after a successful replace so overwriting a cover doesn't leave the
// old image as an orphaned message in the channel forever.
async function telegramDeleteMessage(messageId: number): Promise<void> {
  try {
    const res = await fetch(`https://api.telegram.org/bot${TG_BOT_TOKEN}/deleteMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ chat_id: TG_CHANNEL_ID, message_id: messageId }),
    });
    const data = (await res.json()) as any;
    if (!data.ok) console.warn(`  old cover message delete failed: ${JSON.stringify(data)}`);
  } catch (err) {
    console.warn(`  old cover message delete failed: ${err}`);
  }
}

async function telegramSendDocument(bytes: Uint8Array, filename: string, mimeType: string) {
  for (let attempt = 1; attempt <= UPLOAD_RETRIES; attempt++) {
    try {
      const form = new FormData();
      form.set("chat_id", TG_CHANNEL_ID);
      form.set("document", new Blob([bytes], { type: mimeType }), filename);
      const res = await fetch(`https://api.telegram.org/bot${TG_BOT_TOKEN}/sendDocument`, {
        method: "POST",
        body: form,
      });
      const data = (await res.json()) as any;
      if (!data.ok) throw new Error(`Telegram upload failed for ${filename}: ${JSON.stringify(data)}`);
      return data.result;
    } catch (err) {
      if (attempt === UPLOAD_RETRIES) throw err;
      console.warn(`  Upload attempt ${attempt}/${UPLOAD_RETRIES} failed, retrying: ${err}`);
      await sleep(2000 * attempt);
    }
  }
  throw new Error("unreachable");
}

// Downloads `artworkUrl` and uploads it to Telegram, deleting `previousRef`'s
// message afterward (if any). Returns the new ref string.
async function uploadArtwork(artworkUrl: string, filenameId: string, previousRef: string | null): Promise<string> {
  const imgRes = await fetch(artworkUrl);
  if (!imgRes.ok) throw new Error(`artwork download failed: ${imgRes.status}`);
  const bytes = new Uint8Array(await imgRes.arrayBuffer());
  const contentType = imgRes.headers.get("content-type") ?? "image/jpeg";

  const result = await telegramSendDocument(bytes, `cover-${filenameId}.jpg`, contentType);
  const fileId = result.document?.file_id;
  if (!fileId) throw new Error("Telegram response missing file_id");
  const ref = JSON.stringify({ messageId: result.message_id, fileId });

  if (previousRef) {
    const old = JSON.parse(previousRef) as { messageId: number };
    await telegramDeleteMessage(old.messageId);
  }
  return ref;
}

// Uploads docs/music-cover.jpg once and caches its Telegram ref on disk so
// every subsequent --fallback-cover use just reuses the same ref instead of
// re-uploading -- one message shared by every track that falls all the way
// through to this tier, exactly like the user asked for.
let fallbackCoverRef: string | null = null;
async function getFallbackCoverRef(): Promise<string> {
  if (fallbackCoverRef) return fallbackCoverRef;
  try {
    const cached = JSON.parse(await readFile(FALLBACK_COVER_REF_FILE, "utf-8")) as { ref: string };
    fallbackCoverRef = cached.ref;
    return fallbackCoverRef;
  } catch {
    // not cached yet
  }
  const bytes = await readFile(FALLBACK_COVER_PATH);
  const result = await telegramSendDocument(new Uint8Array(bytes), "fallback-cover.jpg", "image/jpeg");
  const fileId = result.document?.file_id;
  if (!fileId) throw new Error("Telegram response missing file_id for fallback cover");
  fallbackCoverRef = JSON.stringify({ messageId: result.message_id, fileId });
  await writeFile(FALLBACK_COVER_REF_FILE, JSON.stringify({ ref: fallbackCoverRef }));
  return fallbackCoverRef;
}

async function fetchAlbums(): Promise<Album[]> {
  // Deliberately unfiltered by cover_ref here -- eligibility (null cover,
  // --force, or a locally-confirmed AutoGenerated placeholder) is decided
  // per-album in main() via needsFixing(), since that requires a local
  // file read that can't happen inside the SQL query.
  return d1<Album>(
    `SELECT albums.id, albums.name, artists.name AS artist_name, albums.cover_ref,
            (SELECT t.source_path FROM tracks t
             WHERE t.album_id = albums.id AND t.source_path IS NOT NULL LIMIT 1) AS sample_source_path
     FROM albums JOIN artists ON artists.id = albums.artist_id
     ORDER BY albums.name`,
  );
}

// Falls back to per-song matching when the album itself doesn't look like a
// real release on iTunes. Returns every track that still needs a cover,
// applying the same eligibility rule as albums (null cover_ref, --force, or
// a locally-confirmed AutoGenerated placeholder) and skipping ones already
// attempted in a prior run.
async function fetchOutstandingTracks(albumId: string, state: State): Promise<Track[]> {
  const tracks = await d1<Track>(
    `SELECT id, title, cover_ref, source_path FROM tracks WHERE album_id = ? ORDER BY track_no`,
    [albumId],
  );
  const outstanding: Track[] = [];
  for (const t of tracks) {
    if (`track:${t.id}` in state) continue;
    if (await needsFixing(`local-autogen:${t.id}`, t.cover_ref, t.source_path, state)) outstanding.push(t);
  }
  return outstanding;
}

// Deliberately processes every outstanding track for the album in one go
// (not bounded by --limit, which only paces how many albums are visited) —
// track-level state still makes re-running cheap, since already-handled
// tracks are skipped without hitting iTunes again.
async function fixTracks(artistName: string, tracks: Track[], state: State): Promise<number> {
  let fixedCount = 0;

  for (const track of tracks) {
    console.log(`  - ${track.title}`);
    const cleanTitle = cleanTrackTitle(track.title, artistName);
    try {
      let url = await searchSongArtwork(artistName, cleanTitle);
      let status: EntryStatus = "fixed";
      if (!url && LOOSE_FALLBACK) {
        url = await searchLooseArtwork(artistName, cleanTitle);
        status = "fixed-loose";
      }

      if (!url) {
        if (!FALLBACK_COVER) {
          console.log("    no confident match found, skipping");
          state[`track:${track.id}`] = "no-match";
          continue;
        }
        console.log("    no confident match found, using shared fallback cover");
        if (DRY_RUN) {
          state[`track:${track.id}`] = "fixed-fallback";
          fixedCount++;
          continue;
        }
        const ref = await getFallbackCoverRef();
        await d1(`UPDATE tracks SET cover_ref = ? WHERE id = ?`, [ref, track.id]);
        if (track.cover_ref && track.cover_ref !== ref) {
          const old = JSON.parse(track.cover_ref) as { messageId: number };
          await telegramDeleteMessage(old.messageId);
        }
        state[`track:${track.id}`] = "fixed-fallback";
        fixedCount++;
        continue;
      }

      if (DRY_RUN) {
        console.log(`    found (${status}): ${url}`);
        state[`track:${track.id}`] = status;
        fixedCount++;
        continue;
      }

      const ref = await uploadArtwork(url, track.id, track.cover_ref);
      await d1(`UPDATE tracks SET cover_ref = ? WHERE id = ?`, [ref, track.id]);
      console.log(`    updated track cover_ref (${status})`);
      state[`track:${track.id}`] = status;
      fixedCount++;
    } catch (err) {
      console.error(`    failed: ${err}`);
      state[`track:${track.id}`] = "error";
    }
    if (!DRY_RUN) await saveState(state);
  }
  return fixedCount;
}

async function main() {
  const state = await loadState();
  if (RETRY_FAILED) {
    for (const key of Object.keys(state)) {
      if (state[key] === "no-match" || state[key] === "error") delete state[key];
    }
  }

  const albums = await fetchAlbums();
  console.log(
    `${albums.length} album(s) in the library (limit ${LIMIT} this run, force=${FORCE}, dry-run=${DRY_RUN}, loose-fallback=${LOOSE_FALLBACK}).`,
  );

  let albumsFixed = 0;
  let tracksFixed = 0;
  let noMatch = 0;
  let errored = 0;
  let visited = 0;

  for (const album of albums) {
    if (visited >= LIMIT) break;

    const albumNeedsOwnFix = await needsFixing(`local-autogen:${album.id}`, album.cover_ref, album.sample_source_path, state);
    const searchKey = `album-search:${album.id}`;
    const knownNotAnAlbum = state[searchKey] === "no-match";

    if (!albumNeedsOwnFix && !knownNotAnAlbum) continue; // cover's fine, never flagged as a pseudo-album either

    // Already established this isn't a real release -- check whether
    // there's anything left on its tracks before burning an iTunes call or
    // counting against --limit.
    let outstanding: Track[] | null = null;
    if (knownNotAnAlbum) {
      outstanding = await fetchOutstandingTracks(album.id, state);
      if (outstanding.length === 0) continue;
    }

    visited++;
    console.log(`\n${album.artist_name} / ${album.name}`);
    try {
      if (albumNeedsOwnFix && !knownNotAnAlbum) {
        const url = await searchAlbumArtwork(album.artist_name, album.name);
        if (url) {
          console.log(`  found: ${url}`);
          if (!DRY_RUN) {
            const ref = await uploadArtwork(url, album.id, album.cover_ref);
            await d1(`UPDATE albums SET cover_ref = ? WHERE id = ?`, [ref, album.id]);
            console.log("  updated album cover_ref");
          }
          albumsFixed++;
          if (!DRY_RUN) await saveState(state);
          continue;
        }
        state[searchKey] = "no-match";
        console.log("  no confident album match — probably a folder-derived pseudo-album, trying per-song");
      } else if (knownNotAnAlbum) {
        console.log("  (already known: no album-level match) trying per-song");
      }

      const tracks = outstanding ?? (await fetchOutstandingTracks(album.id, state));
      const fixedTracks = await fixTracks(album.artist_name, tracks, state);
      tracksFixed += fixedTracks;
      if (fixedTracks === 0 && tracks.length > 0) noMatch++;
    } catch (err) {
      console.error(`  failed: ${err}`);
      state[searchKey] = "error";
      errored++;
    }

    if (!DRY_RUN) await saveState(state);
  }

  console.log(
    `\nDone. Albums fixed: ${albumsFixed}, tracks fixed individually: ${tracksFixed}, no match: ${noMatch}, errored: ${errored} (out of ${visited} visited this run).`,
  );
}

main();
